name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
    
    - name: Install dependencies
      run: go mod download
    
    - name: Setup test environment
      run: |
        chmod +x scripts/setup_test_env.sh
        source scripts/setup_test_env.sh
    
    - name: Run tests
      run: |
        export GO_TESTING=1
        go test -v ./...
    
    - name: Generate coverage report
      run: |
        export GO_TESTING=1
        go test -v -coverprofile=coverage.out ./...
    
    # Only upload coverage if it exists and the tests pass
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: success() && hashFiles('coverage.out') != ''
      with:
        name: backend-coverage
        path: coverage.out
        if-no-files-found: ignore
  
  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    needs: backend-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install frontend dependencies
      run: cd frontend && npm ci
    
    - name: Build frontend
      run: cd frontend && npm run build
    
    - name: Build backend
      run: go build -v ./cmd/fishki-server
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: fishki-server
        path: fishki-server
        if-no-files-found: error
  
  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      run: cd frontend && npm ci
    
    - name: Run tests
      run: cd frontend && npm test -- --passWithNoTests
  
  frontend-build:
    name: Frontend Build
    runs-on: ubuntu-latest
    needs: frontend-test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      run: cd frontend && npm ci
    
    - name: Build
      run: cd frontend && npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: frontend-build
        path: frontend/dist
        if-no-files-found: error
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
    
    - name: Install golint
      run: go install golang.org/x/lint/golint@latest
    
    - name: Setup test environment
      run: |
        chmod +x scripts/setup_test_env.sh
        source scripts/setup_test_env.sh
    
    - name: Run golint
      run: |
        export GO_TESTING=1
        golint ./... || true  # Don't fail the build if linting issues are found
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      run: cd frontend && npm ci
    
    - name: Run ESLint
      run: cd frontend && npx eslint . --ext .js,.jsx,.ts,.tsx || true  # Don't fail the build if linting issues are found
